In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
sentenses=["i love my dog!!!","I, love my cat","you love my dog","do you think my dog is amazing???","hello you fucking dude dog"]
tokenizer=Tokenizer()
tokenizer.fit_on_texts(sentenses)
print(tokenizer.word_index)

ans = tokenizer.texts_to_sequences(sentenses)
print(ans)

for i in sentenses:
  print(i)
  t=tokenizer.texts_to_sequences([i])
  print(t)

{'my': 1, 'dog': 2, 'love': 3, 'you': 4, 'i': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10, 'hello': 11, 'fucking': 12, 'dude': 13}
[[5, 3, 1, 2], [5, 3, 1, 6], [4, 3, 1, 2], [7, 4, 8, 1, 2, 9, 10], [11, 4, 12, 13, 2]]
i love my dog!!!
[[5, 3, 1, 2]]
I, love my cat
[[5, 3, 1, 6]]
you love my dog
[[4, 3, 1, 2]]
do you think my dog is amazing???
[[7, 4, 8, 1, 2, 9, 10]]
hello you fucking dude dog
[[11, 4, 12, 13, 2]]


In [ ]:
sentenses=["i love my dog!!!","I, love my cat","you love my dog","do you think my dog is amazing???","hello you fucking dude dog abc xyz pqr"]
tokenizer=Tokenizer(num_words=10,oov_token="<oov>")
tokenizer.fit_on_texts(sentenses)
word_index=tokenizer.word_index
sequence=tokenizer.texts_to_sequences(sentenses)
mydata=['i love my amazing dog']
myda=tokenizer.texts_to_sequences(['i love my amazing dog you'])
print(word_index)
print(myda)

{'<oov>': 1, 'my': 2, 'dog': 3, 'love': 4, 'you': 5, 'i': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11, 'hello': 12, 'fucking': 13, 'dude': 14, 'abc': 15, 'xyz': 16, 'pqr': 17}
[[6, 4, 2, 1, 3, 5]]


In [ ]:
t=Tokenizer(oov_token='<oov>')
t.fit_on_texts(['hey there','whats up guys'])
print(t.word_index)
a=['hey whats going there','guys there what']
x=t.texts_to_sequences(a)
print(x)

{'<oov>': 1, 'hey': 2, 'there': 3, 'whats': 4, 'up': 5, 'guys': 6}
[[2, 4, 1, 3], [6, 3, 1]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sen=["i lobve my dog","i love my cat too much","hey there guys i m using whatsapp"]
tokenizer.fit_on_texts(sen)
pa=tokenizer.texts_to_sequences(sen)
padded=pad_sequences(pa,padding="post")
print(padded)
print(tokenizer.word_index)

[[3 1 2 1 0 0 0]
 [3 1 2 1 1 1 0]
 [1 1 1 3 1 1 1]]
{'<oov>': 1, 'my': 2, 'i': 3, 'dog': 4, 'love': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11, 'hello': 12, 'fucking': 13, 'dude': 14, 'lobve': 15, 'too': 16, 'much': 17, 'hey': 18, 'there': 19, 'guys': 20, 'm': 21, 'using': 22, 'whatsapp': 23}


In [ ]:
import json
data = [json.loads(line) for line in open('Sarcasm_Headlines_Dataset.json', 'r')]
print(data[0])

FileNotFoundError: ignored

In [ ]:
sen=[]
url=[]
labels=[]

for item in data:
  sen.append(item['headline'])
  url.append(item['article_link'])
  labels.append(item['is_sarcastic'])



from tensorflow.keras.preprocessing.text import Tokenizer
from  tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer=Tokenizer(oov_token="<oov>")
tokenizer.fit_on_texts(sen)

word_index=tokenizer.word_index

print(word_index)

sequences=tokenizer.texts_to_sequences(sen)


NameError: ignored

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

trainsen=sen[0:int(0.7*(len(sen)))]
testsen=sen[int(0.7*(len(sen))):]
trainlab=np.array(labels[0:int(0.7*(len(sen)))])
testlab=np.array(labels[int(0.7*(len(sen))):])

print(len(trainsen))
print(len(testsen))
print(len(trainlab))
print(len(testlab))

In [ ]:
model=tf.keras.Sequential([ tf.keras.layers.Embedding(10000,16,input_length=120), tf.keras.layers.Flatten(), tf.keras.layers.Dense(6,activation='relu'), tf.keras.layers.Dense(1,activation='sigmoid') ])

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer=Tokenizer(num_words=10000,oov_token="<oov>")
tokenizer.fit_on_texts(trainsen)
word_index=tokenizer.word_index

sequences=tokenizer.texts_to_sequences(trainsen)
padded=pad_sequences(sequences,maxlen=120,truncating='post')


testing_sequences=tokenizer.texts_to_sequences(testsen)
testing_padded=pad_sequences(testing_sequences,maxlen=120,truncating='post')

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

NameError: ignored

In [ ]:
print(type(padded))
print(type(trainlab))
print(type(testing_padded))
print(type(testlab))

<class 'numpy.ndarray'>


NameError: ignored

In [ ]:
history=model.fit(padded,trainlab,epochs=30,validation_data=(testing_padded,testlab),verbose=2)

Epoch 1/30
585/585 - 2s - loss: 0.5922 - accuracy: 0.6720 - val_loss: 0.4680 - val_accuracy: 0.8368
Epoch 2/30
585/585 - 2s - loss: 0.3613 - accuracy: 0.8860 - val_loss: 0.3405 - val_accuracy: 0.8554
Epoch 3/30
585/585 - 2s - loss: 0.1761 - accuracy: 0.9396 - val_loss: 0.3518 - val_accuracy: 0.8557
Epoch 4/30
585/585 - 2s - loss: 0.0967 - accuracy: 0.9693 - val_loss: 0.3932 - val_accuracy: 0.8502
Epoch 5/30
585/585 - 2s - loss: 0.0519 - accuracy: 0.9867 - val_loss: 0.4613 - val_accuracy: 0.8465
Epoch 6/30
585/585 - 2s - loss: 0.0272 - accuracy: 0.9947 - val_loss: 0.5002 - val_accuracy: 0.8441
Epoch 7/30
585/585 - 2s - loss: 0.0145 - accuracy: 0.9979 - val_loss: 0.5569 - val_accuracy: 0.8399
Epoch 8/30
585/585 - 2s - loss: 0.0085 - accuracy: 0.9989 - val_loss: 0.6075 - val_accuracy: 0.8386
Epoch 9/30
585/585 - 2s - loss: 0.0048 - accuracy: 0.9995 - val_loss: 0.6607 - val_accuracy: 0.8388
Epoch 10/30
585/585 - 2s - loss: 0.0030 - accuracy: 0.9995 - val_loss: 0.6903 - val_accuracy: 0.8380

#Assignment of NLP paawansir

In [ ]:
#usage of appropriate libraries 
import nltk,textblob
from nltk import word_tokenize
from textblob import TextBlob
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
from nltk.stem.wordnet import WordNetLemmatizer

#reading the data from text file
corpus="The new era of Deep learnning has foound many widespred uses in diverse fields such as Science, Fashion, Game, Medical,\nHealth etc. which has gained a huge attention for the researchers. Recently, Generative Adversarial Network (GAN) has crucial\ncontribution in the field of medical image analysis, along with diferent variants of GAN it enhances the capability to resolve the\nchallenging problems in medical field which leads to the betterment of healthcar technologies. Furthermore, GAN has proven to\nbe useful, to synthesize images that can resolve the scarcity of real trainng data especially in medical and healthcare field of\nresarch. In this paper, we present an attempt to improve dataset for CT scan images of stomach cancer using GAN approaches to\nvarious fields of medical image analysis. The paper also provides a sttistical comparison of generated images which are found to\nbe of high quality."

#spelling correction
correct_spelled=str(TextBlob(corpus).correct())
corpus=correct_spelled

#tokenization
words=word_tokenize(corpus)

#pos tagging 
pos_tags=nltk.pos_tag(words)

#stopwords removal
stop_words=stopwords.words('english')
without_stopwords=' '.join([word for word in words if word not in stop_words])

#stemming and printing first 10 tokens
stemmer=nltk.stem.PorterStemmer()
stemmed_word_list=[stemmer.stem(word) for word in words]
stemmed_text=' '.join(stemmed_word_list)
print(stemmed_word_list[:10])


#lemmatization and printing first 10 tokens
lemmatizer = WordNetLemmatizer() 
lemmatized_word_list=[lemmatizer.lemmatize(word) for word in words]
lemmatized_text=' '.join(lemmatized_word_list)
print(lemmatized_word_list[:10])


#sentence boundary detection and printing the total number  of sentences
sentences=sent_tokenize(corpus)
print("total no  of sentecnes:"+str(len(sentences)))

LookupError: ignored

In [ ]:
s="The new era of Deep learnning has foound many widespred uses in diverse fields such as Science, Fashion, Game, Medical,\nHealth etc. which has gained a huge attention for the researchers. Recently, Generative Adversarial Network (GAN) has crucial\ncontribution in the field of medical image analysis, along with diferent variants of GAN it enhances the capability to resolve the\nchallenging problems in medical field which leads to the betterment of healthcar technologies. Furthermore, GAN has proven to\nbe useful, to synthesize images that can resolve the scarcity of real trainng data especially in medical and healthcare field of\nresarch. In this paper, we present an attempt to improve dataset for CT scan images of stomach cancer using GAN approaches to\nvarious fields of medical image analysis. The paper also provides a sttistical comparison of generated images which are found to\nbe of high quality."

In [ ]:
s=s.replace("\n"," ")
print(s)

The new era of Deep learnning has foound many widespred uses in diverse fields such as Science, Fashion, Game, Medical, Health etc. which has gained a huge attention for the researchers. Recently, Generative Adversarial Network (GAN) has crucial contribution in the field of medical image analysis, along with diferent variants of GAN it enhances the capability to resolve the challenging problems in medical field which leads to the betterment of healthcar technologies. Furthermore, GAN has proven to be useful, to synthesize images that can resolve the scarcity of real trainng data especially in medical and healthcare field of resarch. In this paper, we present an attempt to improve dataset for CT scan images of stomach cancer using GAN approaches to various fields of medical image analysis. The paper also provides a sttistical comparison of generated images which are found to be of high quality.


In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
corpus=s
corpus

'The new era of Deep learnning has foound many widespred uses in diverse fields such as Science, Fashion, Game, Medical, Health etc. which has gained a huge attention for the researchers. Recently, Generative Adversarial Network (GAN) has crucial contribution in the field of medical image analysis, along with diferent variants of GAN it enhances the capability to resolve the challenging problems in medical field which leads to the betterment of healthcar technologies. Furthermore, GAN has proven to be useful, to synthesize images that can resolve the scarcity of real trainng data especially in medical and healthcare field of resarch. In this paper, we present an attempt to improve dataset for CT scan images of stomach cancer using GAN approaches to various fields of medical image analysis. The paper also provides a sttistical comparison of generated images which are found to be of high quality.'

In [ ]:
correct_spelled=str(TextBlob(corpus).correct())
corpus=correct_spelled
corpus

'The new era of Deep learning has found many widespread uses in diverse fields such as Science, Fashion, Same, Medical, Health etc. which has gained a huge attention for the researches. Recently, Generative Adversarial Network (GAN) has crucial contribution in the field of medical image analysis, along with different variant of GAN it enhanced the capability to resolve the challenging problems in medical field which leads to the betterment of healthcar technologies. Furthermore, GAN has prove to be useful, to synthesis images that can resolve the scarcity of real training data especially in medical and healthcare field of research. In this paper, we present an attempt to improve dataset for of scan images of stomach cancer using GAN approaches to various fields of medical image analysis. The paper also provides a statistical comparison of generate images which are found to be of high quality.'

In [ ]:
nltk.download('averaged_perceptron_tagger')
words=word_tokenize(corpus)

#pos tagging 
pos_tags=nltk.pos_tag(words)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [ ]:
nltk.download('stopwords')
stopwords=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
words=[word for word in words if word not in stopwords]
words

['The',
 'new',
 'era',
 'Deep',
 'learning',
 'found',
 'many',
 'widespread',
 'uses',
 'diverse',
 'fields',
 'Science',
 ',',
 'Fashion',
 ',',
 'Same',
 ',',
 'Medical',
 ',',
 'Health',
 'etc',
 '.',
 'gained',
 'huge',
 'attention',
 'researches',
 '.',
 'Recently',
 ',',
 'Generative',
 'Adversarial',
 'Network',
 '(',
 'GAN',
 ')',
 'crucial',
 'contribution',
 'field',
 'medical',
 'image',
 'analysis',
 ',',
 'along',
 'different',
 'variant',
 'GAN',
 'enhanced',
 'capability',
 'resolve',
 'challenging',
 'problems',
 'medical',
 'field',
 'leads',
 'betterment',
 'healthcar',
 'technologies',
 '.',
 'Furthermore',
 ',',
 'GAN',
 'prove',
 'useful',
 ',',
 'synthesis',
 'images',
 'resolve',
 'scarcity',
 'real',
 'training',
 'data',
 'especially',
 'medical',
 'healthcare',
 'field',
 'research',
 '.',
 'In',
 'paper',
 ',',
 'present',
 'attempt',
 'improve',
 'dataset',
 'scan',
 'images',
 'stomach',
 'cancer',
 'using',
 'GAN',
 'approaches',
 'various',
 'fields',
 